### ISSUE TITLE
[8.x] Missing Locales

### ISSUE THREAD

**Issue by mihob** [craftcms/docker#60]
### Description

For some reason, even with intl extensions installed, all locales except english seem to be missing.

I traced it back to the call ResourceBundle::getLocales('') which is part of the intl extension.

### Steps to reproduce

1. Create or edit a site
2. Try to choose a language, only english and english variantes are available.

![image](https://user-images.githubusercontent.com/48485580/173061296-3dd52d28-d198-477b-977e-9863f69e5eb9.png)

### Additional info

- Craft version: 3.7.44
- PHP version: 8.1.6
- Database driver & version: MySQL 8.0.29
- Plugins & versions:

- CP Field Inspect 1.4.4
- Incognito Field 1.3.0
- MatrixMate 1.4.3
- Redactor 2.10.8
- Sentry Logger 1.2.3

**Comment by thijskaspers** [comment]
Not sure, but this could have to do with the Alpine Linux version that the latest PHP Docker images utilize. Since Alpine Linux 3.16, the ICU locales packages have been divided: `icu-data-en` and `icu-data-full`. Somehow Alpine decided only the first package has to be installed by default.

So possible fixes: downgrade/pin to Alpine Linux 3.15 (image `php:${PHP_VERSION}-${PROJECT_TYPE}-alpine3.15`) or install necessary packages: `apk add icu-data-full` to install all locales.

**Comment by thijskaspers** [comment]
Alpine Linux 3.16 changelog says:

"icu-libs only installs icu-data-en. If additional language support is required, icu-data-full needs to be installed manually."

**Comment by thijskaspers** [comment]
See: https://github.com/craftcms/docker/issues/59#issuecomment-1153741081

@timkelty this issue is preventing people from using Craft with Nitro in their desired locale. If the user doesn't have the Alpine PHP image pulled to their system yet, it will pull the latest version, which is based on Alpine 3.16. The `icu-data-full` package is missing since 3.16, so only English is an option when installing Craft.

**Comment by thijskaspers** [comment]
> (I'm unsure if the `icu-data-full` package is also available for v3.15, so this might throw errors when the system tries to build the image while the build layer is still using 3.15 as the base image instead of 3.16)

Update to confirm `icu-data-full` isn't available on Alpine Linux 3.15. It has been separated from the ICU data package since 3.16, mentioned here: https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.16.0

**Comment by timkelty** [comment]
New images have been pushed to dockerhub – could you try again?

**Comment by Mankeldor** [comment]
In my case this issue is now fixed. :-)

My steps:

1. Destroy nginx containers
2. `brew upgrade`
3. `nitro update`

**Comment by timkelty** [comment]
That's for everyone's help and patience!
